### PR TITLE
refactor: reducing cognitive complexity.

### LINKED ISSUE #114: Reduce cognitive complexity of convertAvroToJsonSchema
#### Describe the bug
[The code complexity is above the recommended threshold.](https://sonarcloud.io/project/issues?id=asyncapi_avro-schema-parser&open=AX3tYnY9la2Sa0kGU2EZ&pullRequest=112&resolved=false&types=CODE_SMELL)

#### How to Reproduce
Run eslint

#### Expected behavior
No warnings.

### PR DESCRIPTION
**Pull request by kolb0401**
## Description

- extracted out union schema logic
- extracted the record schema logic

## Related issue(s)

Resolves #114

### CODE REVIEW

**Comment by kolb0401** [comment]
@derberg @fmvilas @M3lkior @dalelane It's not the prettiest refactor I have ever done but it lowers the cognitive complexity.

**Comment by derberg** [comment]
Lgtm, just please change prefix to "refactor" as you didn't do anything that should trigger release

**Review by fmvilas — APPROVED** [review]
It's better than it was. Thanks! :)

**Pull request merged**
