### PR TITLE
fix: Fix union conversion and int limits

### PR DESCRIPTION
**Pull request by fmvilas**
Unions were not correctly converted and the `int` type wasn't imposing limits.

### CODE REVIEW

**Comment by derberg** [comment]
working on forks in not that hard 😝

**Comment by fmvilas** [comment]
Damn! I forgot again 😄 Forking right now so I don't forget in my next PR.

**Comment by derberg** [comment]
use my script https://gist.github.com/derberg/87319e9c486e4a6c9bef5b629ab0d386 so it is easier for you to sync fork master with upstream master ;)

**Comment by fmvilas** [comment]
That's what I do. I just forgot to use it 😄

**Pull request merged**
